### PR TITLE
Crash on Android 6.0.1 (API 23) due to setInvalidatedByBiometricEnrollment

### PR DESCRIPTION
**Pull request by vxfontes**
When using the plugin on devices running Android 6.0.1 (API 23), the following runtime crash occurs:

```
java.lang.NoSuchMethodError: No virtual method setInvalidatedByBiometricEnrollment(Z)Landroid/security/keystore/KeyGenParameterSpec$Builder; 
in class Landroid/security/keystore/KeyGenParameterSpec$Builder;
```

This happens because the method
KeyGenParameterSpec.Builder#setInvalidatedByBiometricEnrollment(boolean)
was only introduced in Android 7.0 (API 24).

As a result, any device running Android < 24 (e.g., Marshmallow 6.0.1) crashes when trying to initialize the biometric key.

Before (current code):

```
KeyGenParameterSpec.Builder(KEY_NAME,
    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
    .setBlockModes(KeyProperties.BLOCK_MODE_CBC)
    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_PKCS7)
    .setUserAuthenticationRequired(true)
    .setInvalidatedByBiometricEnrollment(true) // <-- crashes on API < 24
    .build()
```

After (fixed code):

```
val builder = KeyGenParameterSpec.Builder(KEY_NAME,
    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
    .setBlockModes(KeyProperties.BLOCK_MODE_CBC)
    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_PKCS7)
    .setUserAuthenticationRequired(true)

// Only call on Android N (API 24) or above
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
    builder.setInvalidatedByBiometricEnrollment(true)
}

keyGenerator.init(builder.build())
keyGenerator.generateKey()
```

Additional improvements applied in my fix like error message or return null

Result:
With this fix, the plugin works correctly on Android 6.0.1 (API 23) and above, maintaining backward compatibility.

### CODE REVIEW

**Comment by iamnabink** [comment]
Thank you for the PR @vxfontes, the enhancements look good. Just before merging, did you thoroughly test these changes and their behavior across different Android API levels (e.g., below and above API 24)?

**Comment by vxfontes** [comment]
Yes @iamnabink, I’ve tested the changes on both older and newer Android versions (including below and above API 24). I also had to apply the plugin locally in production at my work to temporarily solve this issue, and everything has been working as expected.
